### ISSUE TITLE
Unnecessary nested array in example if collection is returned

### ISSUE THREAD

**Issue by tomek-o** [suikabreaker/Janssonpath2#3]
In the test file result value is wrapped in array:
https://github.com/suikabreaker/Janssonpath2/blob/05b6ede9ebb61b84f3e4b4f1ad706ab2a914866e/src/full_test.c#L20
but if result.value is already an array (so when result.is_collection is set?) this creates nested array, not matching http://jsonpath.com result (if this could be treated as reference, I don't have experience in that matter and I'm not sure).

I think if result.is_collection is set then result.value should be dumped directly.

**Comment by suikabreaker** [comment]
This behavior is by design. To distinguish a single element of array type from a bunch of elements that match the condition, this (nested array) is necessary. Janssonpath is not meant to be consistent with http://jsonpath.com (not sure if it is the official implementation?).

However, the design is open to question. If there are strong reasons, I will change the design. In that case, you can reopen the issue.

**Comment by suikabreaker** [comment]
Also, consider that API requires you to `json_decref` the returned node. If array nodes that match the condition should be treated specially, you will also have to treat its reference as an exception.
